import { Runbook } from '../types';

export const standardRunbooks: Runbook[] = [
  {
    id: 'RB-01',
    name: 'Endpoint Isolation & Quarantine',
    category: 'Endpoint',
    description: 'Sever all network interfaces on affected workstation while maintaining EDR management tunnel.',
    estimatedTime: '45s',
    automated: true,
    steps: [
      'Query EDR agent for host ID and active network adapters',
      'Apply dynamic host firewall rule: block all egress except EDR C2 IPs',
      'Terminate active PowerShell/cmd child processes and inject memory dump hook',
      'Verify host status changes to "Quarantined" in central console',
    ],
  },
  {
    id: 'RB-02',
    name: 'Identity Compromise & Token Revocation',
    category: 'Identity',
    description: 'Invalidate all OAuth/OIDC tokens, force password reset, and enable phishing-resistant MFA challenge.',
    estimatedTime: '30s',
    automated: true,
    steps: [
      'Revoke all active refresh tokens in Okta / Microsoft Entra ID',
      'Terminate active browser and desktop SSO sessions',
      'Enforce temporary account lock or require step-up FIDO2 authentication',
      'Notify user via out-of-band SMS/email and stage password reset workflow',
    ],
  },
  {
    id: 'RB-03',
    name: 'C2 Destination Egress Blackhole',
    category: 'Network',
    description: 'Propagate malicious IP and domain indicators to Palo Alto / AWS Network Firewall edge filters.',
    estimatedTime: '20s',
    automated: true,
    steps: [
      'Extract remote indicators of compromise (IPs, FQDNs, URLs)',
      'Push deny rule to perimeter firewalls and Cloudflare edge WAF',
      'Flush local DNS cache and add sinkhole entry in corporate resolver',
      'Audit NetFlow logs for any historical traffic to the blocked destination',
    ],
  },
  {
    id: 'RB-04',
    name: 'Ransomware Emergency Kill-Switch',
    category: 'Ransomware',
    description: 'Halt suspected encryption process trees, freeze shadow copy deletion commands, and isolate share mounts.',
    estimatedTime: '15s',
    automated: true,
    steps: [
      'Trigger kernel-level process freeze on suspicious binaries (vssadmin, bcdedit, cipher)',
      'Unmount all network file shares (SMB/NFS) on target subnet',
      'Verify Volume Shadow Copy service integrity and snapshot status',
      'Alert Incident Commander and generate volatile RAM memory capture',
    ],
  },
  {
    id: 'RB-05',
    name: 'AWS S3 Data Exfiltration Containment',
    category: 'Cloud',
    description: 'Attach emergency deny SCP to compromised IAM role and restrict bucket access to VPC endpoint.',
    estimatedTime: '40s',
    automated: true,
    steps: [
      'Identify IAM principal involved in anomalous GetObject spikes',
      'Attach AWS IAM inline DenyAll policy to principal',
      'Restrict S3 bucket policy to allow only specific internal VPC endpoint',
      'Enable S3 Object Lock and download CloudTrail management event logs',
    ],
  },
  {
    id: 'RB-06',
    name: 'Phishing Tenant Remediation',
    category: 'Network',
    description: 'Purge malicious message copies from all Microsoft 365 / Google Workspace inboxes.',
    estimatedTime: '60s',
    automated: true,
    steps: [
      'Search message trace by InternetMessageId and sender domain',
      'Hard delete all unread and read copies from tenant mailboxes',
      'Check URL click logs to identify if any user clicked the lure',
      'Block sender domain and submit attachment hash to sandbox',
    ],
  },
  {
    id: 'RB-07',
    name: 'Volatile Memory & Forensic Dump',
    category: 'Forensics',
    description: 'Capture full physical RAM and triage artifact bundle (MFT, shimcache, event logs) prior to reboot.',
    estimatedTime: '3m 15s',
    automated: false,
    steps: [
      'Execute forensic agent in read-only mode to capture memory image',
      'Calculate SHA-256 hash of output raw image and store in secure evidence vault',
      'Extract master file table ($MFT) and Windows Event Logs',
      'Generate chain-of-custody cryptographic receipt',
    ],
  },
  {
    id: 'RB-08',
    name: 'Kubernetes Pod Isolation & Container Freeze',
    category: 'Cloud',
    description: 'Apply network policy to block ingress/egress and checkpoint container state for forensics.',
    estimatedTime: '25s',
    automated: true,
    steps: [
      'Cordon worker node to prevent new pod scheduling',
      'Apply strict Calico/Cilium deny NetworkPolicy on pod namespace',
      'Generate CRIU container memory checkpoint for reverse engineering',
      'Inspect service account JWT token for cluster role privilege escalation',
    ],
  },
];
