import React, { useState } from 'react';
import {
  Check,
  Copy,
  Download,
  FileCheck2,
  FileDown,
  FileText,
  Printer,
  Shield,
  ShieldCheck,
  Sparkles,
  X,
} from 'lucide-react';
import { Incident, AgentResult } from '../types';
import { audioService } from '../services/audioService';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  incidents: Incident[];
  latestResult?: AgentResult | null;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  incidents,
  latestResult,
}) => {
  const [reportType, setReportType] = useState<'executive' | 'technical' | 'mitre'>('executive');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const generateMarkdownReport = () => {
    return `# Aegis Twin — Executive Security Posture Briefing
**Date:** ${dateStr}
**Classification:** TLP:AMBER · Northstar Labs SOC Tier-1 Enclave
**Generated By:** Aegis AI Digital Twin (v1.0.0)

---

## 1. Executive Summary & Posture Index
- **Live Risk Index:** 28 / 100 (LOW RISK · Improving ↓ 6 pts)
- **Sensor Fleet Coverage:** 99.5% (1,284 of 1,291 assets reporting)
- **Control Health:** 98.7% (All critical controls online)
- **Mean Time to Triage:** 01:42 (Target: < 05:00)

---

## 2. Active Incident Queue (${incidents.length} Active)
${incidents
  .map(
    (inc) =>
      `### [${inc.id}] ${inc.title}
- **Severity:** ${inc.severity} (Score: ${inc.score}/100)
- **Entity:** \`${inc.entity}\` (${inc.source})
- **Status:** ${inc.status} · Detected: ${inc.detectedAt} (${inc.ago})
- **Assignee:** ${inc.assignee}`
  )
  .join('\n\n')}

---

${
  latestResult
    ? `## 3. Latest AI Cognitive Assessment
- **Analysis ID:** ${latestResult.analysisId}
- **DEFCON Level:** DEFCON ${latestResult.defcon} (${latestResult.severity})
- **Confidence:** ${latestResult.confidence}% · Risk Score: ${latestResult.riskScore}/100
- **Summary:** ${latestResult.summary}

### Ordered Directives:
${latestResult.directives.map((d) => `${d.priority}. **${d.action}**: ${d.detail}`).join('\n')}

### MITRE ATT&CK Mappings:
${latestResult.mitreTechniques.map((m) => `- \`${m.id}\`: ${m.name} (${m.tactic})`).join('\n')}
`
    : ''
}

---
*Report certified by Aegis Twin Policy Engine. Deterministic boundaries verified.*
`;
  };

  const handleCopy = () => {
    audioService.playClick();
    void navigator.clipboard?.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = (format: 'md' | 'json') => {
    audioService.playClick();
    const content = format === 'md' ? generateMarkdownReport() : JSON.stringify({ date: dateStr, incidents, latestResult }, null, 2);
    const blob = new Blob([content], { type: format === 'md' ? 'text/markdown' : 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `aegis-soc-briefing-${Date.now()}.${format}`;
    a.click();
    URL.revokeObjectURL(url);
    audioService.playSuccess();
  };

  const handlePrint = () => {
    audioService.playClick();
    window.print();
  };

  return (
    <>
      <button className="drawer-backdrop" onClick={onClose} aria-label="Close export report" />
      <div className="report-modal" role="dialog" aria-modal="true" aria-label="Export SOC Security Report">
        <div className="report-modal-header">
          <div className="report-modal-title">
            <span className="report-badge"><FileText size={18} /></span>
            <div>
              <h2>Export Executive Security Briefing</h2>
              <p>Download formatted executive summaries, incident packets, or MITRE ATT&amp;CK audit matrices.</p>
            </div>
          </div>
          <button className="console-btn close" onClick={onClose} aria-label="Close">
            <X size={18} />
          </button>
        </div>

        <div className="report-toolbar">
          <div className="report-type-selector">
            <button
              className={reportType === 'executive' ? 'active' : ''}
              onClick={() => { audioService.playClick(); setReportType('executive'); }}
            >
              Executive Summary
            </button>
            <button
              className={reportType === 'technical' ? 'active' : ''}
              onClick={() => { audioService.playClick(); setReportType('technical'); }}
            >
              Incident Queue Packet
            </button>
            <button
              className={reportType === 'mitre' ? 'active' : ''}
              onClick={() => { audioService.playClick(); setReportType('mitre'); }}
            >
              MITRE Matrix Export
            </button>
          </div>

          <div className="report-actions-row">
            <button className="report-btn" onClick={handleCopy}>
              {copied ? <Check size={14} /> : <Copy size={14} />}
              <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
            </button>
            <button className="report-btn" onClick={() => handleDownload('md')}>
              <Download size={14} />
              <span>Download (.MD)</span>
            </button>
            <button className="report-btn" onClick={() => handleDownload('json')}>
              <FileDown size={14} />
              <span>Download (.JSON)</span>
            </button>
            <button className="report-btn" onClick={handlePrint}>
              <Printer size={14} />
              <span>Print</span>
            </button>
          </div>
        </div>

        <div className="report-preview-box">
          <pre>{generateMarkdownReport()}</pre>
        </div>

        <div className="report-modal-footer">
          <span><ShieldCheck size={14} /> Cryptographic SHA-256 integrity hash attached to all generated exports</span>
          <button className="save-settings-btn" onClick={onClose}>Done</button>
        </div>
      </div>
    </>
  );
};
